---
title: "RMarkdown Assignment"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

My name is Serhan Süer. I'm not working now and searching job opportunities. I have graduated from Yeditepe University Business Administration Department. My special interest related to data analytics is marketing analytics and brand management activities. I'm planning to use data science skills in my future work in order to recognise our customers' characteristics and preferences. I’m also planning to use them to obtain useful data visualizations and develop predictive modeling.


## Video Summary: Moving from Prototype to Production in R
This video is about some of the issues around taking a model from prototype and then making it usable to stakeholders. It also explains best practices around designing machine learning system. After that, the speaker introduces the Metaflow and its applications on the project he has been working on at Netflix.

[Video Link](https://www.youtube.com/watch?v=dLKky1xIxtc&t=15s)


## First Post : Advanced Marketing Applications by Mohammad Shadan
In this post, the author starts with explaining that reducing the data to its underlying dimensions allows us more clearly identify the relationships among concepts. Then he continues with clarifying three common methods to reduce complexity by reducing the number of dimensions in the data: Principal component analysis (PCA), Exploratory factor analysis (EFA) and Multidimensional scaling (MDS). Then he gives some definitions and areas of usage of these methods respectively and explains how we use them in R in order to identify more clearly the relationships among concepts.

[Post Link](https://rpubs.com/mohammadshadan/AdvancedMarketingApplications)


## Second Post : Analyzing Direct Marketing Data with R by Liang Wei and Brendan Kitts
This post begins with introducing their company(Lucid Commerce) and business problems they're generally faced with. Then they explain why they choose R in their company and how R offers them many advantages related to advance analytics. Also they try to show these advantages with a case study. They express the R Analytics Workflow with a chart and bring a business problem up to solve with this workflow step by step. These steps contain data visualization, building SSRS Report, stored procedure, R script snippet, forecasting model and publishing forecasting results. Finally, they summarize the business problem and the steps of the workflow.

[Post Link](https://www.r-project.org/conferences/useR-2010/slides/Wei+Kitts.pdf)


## Third Post : Market Basket Analysis using R by Hafsa Jabeen
In this post, Hafsa Jabeen introduces Market Basket Analysis and the APRIORI Algorithm that works behind it. He also highlights how it is helping retailers boost business by predicting what items customers buy together. Firstly, she explains Association Rule Mining and applications related to Market Basket Analysis. Secondly, she expresses APRIORI Algorithm and its relationship with Association Rule Mining and Market Basket Analysis. Finally, she shows how to implement MBA/Association Rule Mining using R with visualizations.

[Post Link](https://www.datacamp.com/community/tutorials/market-basket-analysis-r)